/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'a13446' at '15/11/05 11:52' with Gradle 2.8
 *
 * @author a13446, @date 15/11/05 11:52
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
